---

#########
# Files #
#########

_forum_files:

  - path:  "{{ _forum_dir }}/install"
    state: absent
  - path:  "{{ _forum_dir }}/files"
    state: directory
    owner: "{{ _user }}"
    group: users
    acls:
      - "user:{{ elao_php_user }}:rwx"
      - "user:{{ _user }}:rwx"
      - "default:user:{{ elao_php_user }}:rwx"
      - "default:user:{{ _user }}:rwx"
  - path:  "{{ _forum_dir }}/cache"
    state: directory
    owner: "{{ _user }}"
    group: users
    acls:
      - "user:{{ elao_php_user }}:rwx"
      - "user:{{ _user }}:rwx"
      - "default:user:{{ elao_php_user }}:rwx"
      - "default:user:{{ _user }}:rwx"
  - path:  "{{ _forum_dir }}/store"
    state: directory
    owner: "{{ _user }}"
    group: users
    acls:
      - "user:{{ elao_php_user }}:rwx"
      - "user:{{ _user }}:rwx"
      - "default:user:{{ elao_php_user }}:rwx"
      - "default:user:{{ _user }}:rwx"
  - path:  "{{ _forum_dir }}/images/avatars/upload"
    state: directory
    owner: "{{ _user }}"
    group: users
    acls:
      - "user:{{ elao_php_user }}:rwx"
      - "user:{{ _user }}:rwx"
      - "default:user:{{ elao_php_user }}:rwx"
      - "default:user:{{ _user }}:rwx"
  - path:  "{{ _forum_dir }}/video.php"
    state: file
    owner: "{{ _user }}"
    group: users
    template: "{{ playbook_dir ~ '/files/phpBB/video.php' }}"
  - path:  "{{ _forum_dir }}/config.php"
    owner: "{{ _user }}"
    group: users
    content: |
      <?php
      // phpBB 3.0.x auto-generated configuration file
      // Do not change anything in this file!
      $dbms = 'mysql';
      $dbhost = '127.0.0.1';
      $dbport = '';
      $dbname = 'bepro_forum';
      $dbuser = 'bepro_forum';
      $dbpasswd = '{{ _forum_db_password }}';
      $table_prefix = '';
      $acm_type = 'file';
      $load_extensions = '';

      @define('PHPBB_INSTALLED', true);
      // @define('DEBUG', true);
      // @define('DEBUG_EXTRA', true);

#######
# Php #
#######

elao_php_version: 5
elao_php_sapis: ['cli', 'fpm']

elao_php_fpm_pools_exclusive: true
elao_php_fpm_pools:
  - file:     www.conf
    template: fpm_pools/www_{{ _env }}.conf.j2

elao_php_extensions:
  - curl
  - mysqlnd

elao_php_configs_exclusive: true
elao_php_configs:
  - file: 50-opcache.ini
    template: configs/opcache_{{ _env }}.ini.j2
  - file: 60-config.ini
    template: configs/{{ _env }}.ini.j2
    config:
      - date.timezone: Europe/Paris
      # App
      - upload_max_filesize: 20M
      - post_max_size:       20M

#########
# Nginx #
#########

elao_nginx_config_template: config/http_{{ _env }}.conf.j2

elao_nginx_configs_exclusive: false
elao_nginx_configs:
  # Php fpm
  - file:     php_fpm_params
    template: configs/php_fpm_params_{{ _env }}.j2
  # Gzip
  - file:     gzip
    template: configs/gzip_{{ _env }}.j2
  # Default 404
  - file:     00-default.conf
    template: configs/server_{{ _env }}.conf.j2
    config:
      - return: 404
  # App
  - file:     "{{ _forum_host }}.conf"
    template: configs/server_{{ _env }}.conf.j2
    config:
      - server_name: "{{ _forum_host }}"
      - root:        "{{ _forum_dir }}"
      - access_log:  "{{ elao_nginx_log_dir }}/app.access.log"
      - error_log:   "{{ elao_nginx_log_dir }}/app.error.log"
      - include:     conf.d/gzip
      - location /:
        - index: index.php index.html index.htm
      - location ~ /(config\.php|common\.php|includes|cache|files|store|images/avatars/upload):
        - deny: all
      - location ~ \.php(/|$):
        - include: conf.d/php_fpm_params
      # App
      - client_max_body_size: 20M
